import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "./components/ui/header";
import Footer from "./components/ui/footer";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body 
        className={cn("flex flex-col min-h-screen bg-background font-sans antialiased", inter.className )}>
          <Header />
          <main className="flex-grow bg-gradient-to-br from-blue-100 to-indigo-100">
            {children}
          </main>
          <Footer />
        </body>
    </html>
  );
}
